### ISSUE TITLE
Depreciation of k8s-at-home charts

### ISSUE THREAD

**Issue by axeII** [axeII/home-ops#270]
https://discord.com/channels/673534664354430999/779882873204506624/1010643162332668094

> Over careful debate with some community members, @bjw-s (Bernd)  and I have decided to deprecate the charts repository. While this won’t be a popular decision we’re sure, what we started years ago was a great learning experience but has been a growing amount of effort to maintain in our free time. The unfortunate fact is we do not see much help from the community on issues or fixing problems in application helm charts and that leaves the burden on a few maintainers to help out. To those that were helping we greatly appreciate all the effort you’ve done.

Migrate all services from `k8s-at-home` to `bjw-s-charts` https://github.com/bjw-s/helm-charts

Example: 
```yaml
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
```
