### ISSUE TITLE
Fix: Issue with deploy nvidia runtime.

### ISSUE THREAD

**Issue by axeII** [axeII/home-ops#436]
Seems like no matter what I try fedora simply makes problem to deploy pod with nvidia runtime class. 

I tried: https://bytemeta.vip/index.php/repo/NVIDIA/k8s-device-plugin/issues/275?page=1 if some packages are wrong. 

Official docs here: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html

**Comment by axeII** [comment]
Fixed. This helped but is old and obsolite: https://itnext.io/enabling-nvidia-gpus-on-k3s-for-cuda-workloads-a11b96f967b0

* to test you need image  nvidia/cuda:11.0.3-base.
* also don't use the templ just the defualt nvidia confit.toml. 


```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  containers:
    - name: cuda-container
      image: nvidia/cuda:11.0.3-base
      command: ["nvidia-smi"]
  nodeSelector:
    nvidia.com/gpu: "true"

```
